modules/logging/images.yml

Due to the WIP https://github.com/sighupio/fury-kubernetes-logging/pull/67 i'm adding the required images

[FEATURE] Add Opensearch images

---

.github/workflows/sync-dr.yml
.github/workflows/sync-extra.yml
.github/workflows/sync-ingress.yml
.github/workflows/sync-keycloak.yml
.github/workflows/sync-kong.yml
.github/workflows/sync-logging.yml
.github/workflows/sync-monitoring.yml
.github/workflows/sync-networking.yml
.github/workflows/sync-on-premises.yml
.github/workflows/sync-opa.yml
.github/workflows/sync-postgresql.yml
.github/workflows/sync-redis.yml
.github/workflows/sync-registry.yml
.github/workflows/sync-service-mesh.yml

Hi team, i did a quick and dirty split of all the jobs to parallelise the sync execution
see #43

[FEATURE] - parallel sync jobs

---

modules/service-mesh/images.yml

As per PR title. Related to https://github.com/sighupio/fury-kubernetes-service-mesh/pull/15

Added istio images 1.9.5

---

modules/kong/images.yml

This is a pre-requisites to upgrade the add-on Kong Fury module

[FEATURE] - upgrade kong images

---

modules/monitoring/images.yml

Update Prometheus image

---

modules/monitoring/images.yml

Updated Alertmanager image

---

modules/monitoring/images.yml

Update kube-state-metrics image

---

modules/monitoring/images.yml

Add blackbox-exporter image

---

modules/monitoring/images.yml

Update images needed by Grafana

---

modules/monitoring/images.yml

Update prometheus-adapter image

---

modules/monitoring/images.yml

Update Goldpinger image

---

modules/monitoring/images.yml

Update x509-certificate-exporter image

---

modules/auth/images.yml
modules/ingress/images.yml
modules/on-premises/images.yml

- create auth module
- move already existing images for Dex and Pomerium to auth module
- add Gangway image sync

feat: add auth module and move images

---

README.md
modules/monitoring/custom/grafana/Dockerfile
modules/monitoring/images.yml
single_sync.sh

Add container image building capabilities

---

.github/workflows/sync-aws.yml
modules/aws/images.yml

feat: add aws pipeline, and add aws-node-termination-handler image

---

modules/aws/images.yml

feat: add aws load balancer controller image

---

modules/aws/images.yml

feat: add ebs csi driver images

---

modules/aws/images.yml

feat: add csi-snapshotter image

---

modules/monitoring/images.yml

Add x509-exporter v3.4.0

---

modules/ingress/images.yml

feat: add nginx v1.3.1

---

.github/workflows/sync-storage.yml
modules/storage/images.yml

As per PR title. I forgot to add it in the previous PR. 😅

Added GitHub workflow for storage module images

---

modules/service-mesh/images.yml

Changes to add istio operator 1.15.4

feat(service-mesh): add istio v1.15.4 images

---

modules/registry/images.yml

added version v2.7.0 on components used by Harbor

feat (registry): add harbor v2.7.0 images

---

modules/monitoring/images.yml

**grafana:** https://github.com/grafana/grafana/releases/tag/v9.3.6  
**k8s-sidecar:** https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.22.2

feat(grafana): add new image versions

---

modules/monitoring/images.yml

Added images for upgrading the prometheus and prometheus operator, WIP for -> [issue-126](https://github.com/sighupio/fury-kubernetes-monitoring/issues/126)

feat: add images for prometheus operator for update to v0.62.0

---

modules/monitoring/images.yml

Added images for upgrading the prometheus adapter, WIP for -> [issues-125](https://github.com/sighupio/fury-kubernetes-monitoring/issues/125)

feat: update prometheus adapter to 0.10.0

---

modules/auth/images.yml

feature(auth): add pomerium nonroot v0.21.0

---

modules/monitoring/images.yml

Added images for upgrading the alertmanager , WIP for -> [issues-120](https://github.com/sighupio/fury-kubernetes-monitoring/issues/120)

Add image for alermanager 0.25.0

---

modules/monitoring/images.yml

Added images for upgrade thanos , WIP for -> [issues-128](https://github.com/sighupio/fury-kubernetes-monitoring/issues/128)

Add thanos images for v0.30.2

---

modules/networking/images.yml

feat: add cilium images

---

modules/monitoring/images.yml

Add a new destination to [solve the discussion problem](https://github.com/sighupio/fury-kubernetes-monitoring/pull/146#discussion_r1143436235)

fix: add destination to thanos sync

---

modules/keycloak/custom/keycloak/Dockerfile
modules/keycloak/images.yml

Adding the following images:
- Keycloak operator
- Keycloak from Quay registry (for now I would keep both versions for retro-compatibility)
- Keycloak with [SPI metrics](https://github.com/aerogear/keycloak-metrics-spi) plugin installed

Add Keycloak v21.1.1

---

modules/service-mesh/images.yml

added new images for Istio and Kiali

feat(service-mesh): add istio v1.17.2 - kiali 1.63.2 images

---

modules/service-mesh/images.yml

feat(service-mesh): updated kiali 1.63.2 image

---

modules/ingress/images.yml

updated image nginx controller to "v1.7.1"

feat: update ingress nginx controller

---

modules/opa/images.yml

add new versions for OPA module components

feat(opa): add new versions

---

modules/extra/images.yml

Import local-path-provisioner v0.0.24 in workshop project.

feat(workshop): import local-path-provisioner v0.0.24

---

modules/extra/images.yml

Added image for NFS subdir external provisioner

feat: add image for NFS subdir external provisioner

---

modules/on-premises/images.yml

Added images for the following components:
- **coredns**: v1.6.7, v1.7.0
- **kube-apiserver**: v1.18.14, v1.20.15
- **kube-controller-manager**: v1.18.14, v1.20.15
- **kube-proxy**: v1.18.14, v1.20.15
- **kube-scheduler**: v1.18.14, v1.20.15

feat: add images for core components

---

modules/service-mesh/images.yml

added istio images with version 1.16.7

Added istio 1.16.7 images

---

modules/networking/images.yml

feat: update images for calico 3.26.1

---

modules/aws/images.yml

feat: update aws images for 1.26

---

modules/aws/images.yml

Feat/update aws images for 1.26

---

modules/extra/images.yml

feat: add kindest node 1.27.1

---

modules/dr/images.yml

Container image sync for fury-kubernetes-dr v2.2.0

feat: add v1.27 dr images

---

modules/service-mesh/images.yml

I've simply upgraded all the kong-mesh / kuma images to v2.4.3 and changed the order of the versions to follow the pattern of the other modules.

Feat/service mesh/kuma kong mesh v2.4.3

---

modules/opa/images.yml

feat(opa): add GPM v1.0.9

---

modules/opa/images.yml

For a more comprehensive understanding of this release, please refer to:
https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.14.0

feat(opa): add gatekeeper 3.14

---

.github/workflows/sync-aws.yml
.github/workflows/sync-extra.yml
.github/workflows/sync-logging.yml
.github/workflows/sync-networking.yml
modules/aws/images.yml
modules/extra/images.yml
modules/logging/images.yml
modules/networking/images.yml

This PR adds all the images in multi-arch mode needed for workers. Tested on EKS

feat: ARM images needed for worker nodes (main daemonsets)

---

modules/opa/images.yml

feat(opa,kubectl): bump to 1.27.10

---

modules/on-premises/images.yml

Add images for k8s on-prem 1.28.7

feat(on-prem): v1.28.7

---

.github/workflows/sync-on-premises.yml
modules/on-premises/images.yml

feat: multi-arch sync also for kubernetes images

---

modules/networking/images.yml

as per title
CC: @ettoreciarcia

feat: add missing calico images for 3.27.0 version

---

modules/vsphere/images.yml

Hello there,
This PR imports into SIGHUP's registry all the vSphere images from all versions of fury-kubernetes-vsphere module
- https://github.com/sighupio/fury-kubernetes-vsphere/issues/3

Images for fury-kubernetes-vsphere

---

.github/workflows/sync-ingress.yml
modules/ingress/images.yml

- add nginx v1.11.2 to the synced images
- add multiarch to nginx images

feat(ingress): sync nginx v1.11.2 and enable multiarch

---

.github/workflows/sync-trivy.yml
modules/trivy/images.yml

Sync Trivy database in registry.sighup.io/fury-secured.
It's useful to avoid rate limit issue

feat(trivy): add trivy-db and trivy-java-db sync

---

modules/service-mesh/images.yml

feat(service-meash): jaeger version Bump

---

modules/extra/images.yml

feat: add kindtest v1.30.4 and v1.31.0

---

modules/dr/images.yml

minio/minio -> RELEASE.2024-10-13T13-34-11Z
minio/mc -> RELEASE.2024-10-08T09-37-26Z

feat(modules,dr): update minio/minio and minio/mc

---

modules/storage/images.yml

feat: add trident images for delivery purposes

---

modules/opa/images.yml

- Needed by https://github.com/sighupio/fury-kubernetes-opa/pull/111

feat(opa): add GPM v1.0.13

---

modules/on-premises/images.yml

feat: bump the new k8s version with the real latest

---

modules/dr/images.yml

Upgrade minio images to RELEASE.2024-11-*.

feat(minio): upgrade images to RELEASE.2024-11

---

modules/service-mesh/images.yml

[FEAT] add images for istio 1.24

---

modules/storage/images.yml

As per title
ps. mind if u like the the destination

[FEAT] add manage per new sig images: Vsphere CSI-PV

---

modules/logging/images.yml

This PR fixes a typo in the mentioned image tag.

fix(logging): fix prometheus community es exporter img tag

---

modules/monitoring/images.yml

add v1.8.2 to prometheus node-exporter versions

feat(images): add v1.8.2 to prometheus node-exporter versions

---

modules/extra/images.yml
modules/monitoring/images.yml

Add new images:
configmap-reloader
blackbox-exporter versions
kube-rbac-proxy

feat(images): update configmap-reloader and blackbox-exporter versions

---

modules/extra/images.yml
modules/monitoring/images.yml

add v0.12.0 tag for prometheus-adapter

feat(images): add v0.12.0 tag for prometheus-adapter

---

modules/monitoring/images.yml

add Prometheus image version v2.54.1 to images.yml

feat: add Prometheus image version v2.54.1 to images.yml

---

modules/monitoring/images.yml

add new Prometheus operator image version v0.76.2

feat: add new Prometheus operator image version v0.76.2

---

modules/monitoring/images.yml

add Grafana image version v11.3.0

feat: add Grafana image version v11.3.0

---

modules/monitoring/images.yml
modules/networking/images.yml

fix typo in Calico Node 3.29 image tag.

fix(networking): typo in Calico Node 3.29 image tag

---

modules/service-mesh/images.yml

feat: added jaeger 1.62

---

modules/aws/images.yml

feat(autoscaler): add newer version to 1.29.5

---

modules/stakater/images.yml

This PR adds the Stakater Reloader to the Fury Image registry.
- Added version v1.2.1 of Stakater Reloader

feat: add stakater reloader

---

modules/kong/images.yml

This PR adds Kong Deck to the Fury Image Registry
- Added version v1.44.2 of Kong Deck

feat: add deck for kong module

---

modules/tracing/images.yml

Updated tracing images for 1.32

feat(tracing): update tracing images for 1.32 upgrade

---

modules/dr/images.yml

feat(dr): update minio

---

modules/auth/images.yml

feat(auth): update images

---

modules/dr/custom/etcd-backupper/Dockerfile
modules/dr/custom/etcd-backupper/init.sh

This adds a simple sanity check before pushing it into S3.

Add snapshot verification before pushing it to s3

---

modules/logging/images.yml

Required by [#568](https://github.com/sighupio/product-management/issues/568)

feat: add new versions of opensearch images

---

modules/dr/images.yml

Required for https://github.com/sighupio/product-management/issues/626

feat(dr): update velero images

---

modules/dr/images.yml

Required for https://github.com/sighupio/product-management/issues/626

feat(dr): update csi snapshotter for 1.32

---

modules/aws/images.yml

required by https://github.com/sighupio/fury-kubernetes-aws/pull/88

feat(aws,cluster-autoscaler): add image v1.32.0

---

modules/networking/images.yml

Add cilium 1.17.2 and hubble 0.13.2

feat: add cilium v1.17.2 and hubble 0.13.2

---

modules/ingress/images.yml

Add new Ingress controller image to fix Nginx CVE.

Add new version of ingress-nginx

---

modules/storage/images.yml

bump image for new storage module version

feat: add new images for storage add on

---

modules/service-mesh/images.yml

As per title
ps. we should remove the deprecated images.

feat: all images for rework on istio addon

---

modules/on-premises/images.yml

feat: bump kubernetes images to support v1.32.4

---

.github/workflows/cve-scan-and-patching.yml
CVEs/v1.32.0-rc.2/furyctl.yaml
CVEs/v1.32.0/furyctl.yaml

This PR:
- adds SD v1.32.0-rc.2 to CVE scan workflow
- temporarily adds in that workflow an RC of furyctl

feat: add SD v1.32.0 to cve-scan-and-patching workflow

---

modules/storage/images.yml

Added latest rook image for releasing the new version of add-on-storage

feat(rook): Add latest version of rook to images

---

modules/dr/images.yml

Updated the images for the new Velero package version.

Update images for Velero

---

modules/auth/images.yml

Adding 0.30.5 to the pomerium versions

feat: add pomerium 0.30.5

---

modules/on-premises/images.yml

feat: update coredns to v1.12.0
