sighupio/container-image-sync

modules/service-mesh/images.yml

As per PR title. This is required, since Kuma uses different images from Kong Mesh.

Kuma images 1.4.1

---

single_sync.sh

fixing `if` construct when image must be skipped, add `-n` flag on skopeo command to skip tags on response (we only use layers), not compatible with ecr sources

fix: sync script

---

modules/monitoring/images.yml

Import prometheus-adapter v0.5.0
The image is downloaded from quay.io to avoid PullRateLimits from DockerHub and because versions previous `v0.8.4` are not available from k8s.gcr.io registry.
References:
- https://github.com/kubernetes-sigs/prometheus-adapter/releases/tag/v0.5.0
- https://github.com/kubernetes-sigs/prometheus-adapter#official-images

feat(monitoring): add prometheus-adapter v0.5.0

---

modules/keycloak/custom/keycloak/Dockerfile

Changed the download method, since `curl` is not available in the image.

Fix Keycloak image

---

modules/logging/images.yml

According to the [Graceful draining feature](https://kube-logging.dev/docs/logging-infrastructure/fluentd/#graceful-draining) on the kube-logging operator, import the images used for draining buffers when scaling down fluentd instances.
The images have been imported according to the following artifact pages:
- [Banzai cloud](https://github.com/orgs/banzaicloud/packages/container/package/fluentd-drain-watch)
- [Kube Logging](https://github.com/kube-logging/fluentd-drain-watch/pkgs/container/fluentd-drain-watch)

Images for gracefully draining fluentd buffers when scaling instances

---

.github/workflows/dry.yml
.github/workflows/sync-auth.yml
.github/workflows/sync-aws.yml
.github/workflows/sync-dr.yml
.github/workflows/sync-extra.yml
.github/workflows/sync-ingress.yml
.github/workflows/sync-kafka.yml
.github/workflows/sync-keycloak.yml
.github/workflows/sync-kong.yml
.github/workflows/sync-logging.yml
.github/workflows/sync-monitoring.yml
.github/workflows/sync-networking.yml
.github/workflows/sync-on-premises.yml
.github/workflows/sync-opa.yml
.github/workflows/sync-postgresql.yml
.github/workflows/sync-redis.yml
.github/workflows/sync-registry.yml
.github/workflows/sync-service-mesh.yml
.github/workflows/sync-storage.yml
.github/workflows/sync-vault.yml

feat: update skopeo stable to v1.13 (v1.9 has expired on quay)

---

modules/ingress/images.yml

Added a new step to pull the external-dns image from the new registry

feat(ingress): add image for external-dns v0.13.6

---

modules/networking/images.yml

Includes calico and calico operator images for KFD 1.27.
- Tigera operator v1.30.7
- Calico images v3.26.3

feat(networking): add calico and tigera images for 1.27

---

modules/networking/images.yml

fix: missing calico image for 3.26.3

---

modules/networking/images.yml

Import the images for upgrading calico to version v3.27.0.

Calico v3.27.0

---

modules/ingress/images.yml

This PR updates Cert-Manager to version 14.2, introducing a new ACME Solver image:
- Upgraded Cert-Manager to v14.2.
- Added ACME Solver image

feat(cert-manager): version bump 14.2 add ACME solver

---

modules/networking/images.yml

enable multi-archi sync for Cilium images, otherwise Colium pods won't come up even having multi-arch support at CRI level.

feat(networking): enable multi-arch for Cilium

---

modules/monitoring/custom/grafana/Dockerfile
modules/monitoring/images.yml

This change does the following:
- updates `grafana-cli` to `grafana cli` because of deprecation
- creates a new image called `grafana-kuma` based on the same Dockerfile, but it also installs the [Kuma Datasource plugin](https://github.com/kumahq/kuma-grafana-datasource)
- since this plugin is not signed, we also need to tell Grafana to allow this unsigned plugin explicitly: this is done by the variable `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS` which does not affect the original image, since it's empty at build time
Another option could be to install this plugin in our Grafana image always

feat(monitoring): add grafana kuma plugin

---

modules/vsphere/images.yml

Add images for kubernetes v1.28 and v1.29 clusters using vSphere CPI and CSI.

vSphere CSI v3.2.0 and CPI v1.28.1, v1.29.0

---

modules/extra/images.yml

- add busybox `stable`, needed for https://github.com/sighupio/fury-kubernetes-auth/pull/28

feat(extra): add busybox stable

---

modules/storage/images.yml

Added `registry.sighup.io/fury/sig-storage/nfs-subdir-external-provisioner`

feat(modules,storage): add nfs-subdir-external-provisioner image

---

modules/on-premises/images.yml

feat: bump kubernetes images used in 1.30.5, 1.29.9 and 1.28.14

---

modules/logging/images.yml

This PR adds loki v2.9.10 image for loki-distributed upgrade.

feat(logging): add loki v2.9.10

---

modules/monitoring/images.yml

add v2.13.0 tag for kube-state-metrics

feat(images): add v2.13.0 tag for kube-state-metrics

---

modules/redis/images.yml

This PR adds the redis 7.4.2-alpine3.21 image for the fury registry.
- Added version 7.4.2 of Redis using Alpine 3.21

feat: add redis 7.4.2-alpine3.21

---

modules/dr/custom/etcd-backupper/Dockerfile
modules/dr/custom/etcd-backupper/README.md
modules/dr/custom/etcd-backupper/init.sh

Since the `etcdctl snapshot save` command needs one and only one endpoint to perform the snapshot, we need to choose which one. This is chosen by asking the whole etcd cluster which node is healthy, then we snapshot that node.

Add multi-node support and failure resiliency to etcd-backupper

---

modules/monitoring/images.yml

Hi there!
The PR includes the images required for the `fury-kubernetes-monitoring` v3.4.0 release. The PR includes:
- alertmanager:v0.27.0
- x509-certificate-exporter:3.18.1
- grafana/mimir:2.15.0

feat(monitoring): bump images for 1.32 release

---

modules/logging/images.yml

This PR adds the loki 3.4.2 and nginx 1.27.3-alpine image for the fury registry.
- Added version 3.4.2 of Loki
- Added version 1.27.3 of nginx using Alpine

feat(logging): add loki 3.4.2 and nginx 1.27.3-alpine

---

modules/logging/images.yml

needed for [#566](https://github.com/sighupio/product-management/issues/566)
from Logging Operator v5.1.0:
> Changes in Fluentd images
>
> Earlier, Logging operator used Fluentd images published at https://github.com/kube-logging/fluentd-images,
> and its version numbers followed the official Fluentd version numbers.
> From now on, we build Fluentd images from our repository (https://github.com/kube-logging/logging-operator/tree/master/images/fluentd)
> and its version numbering follows the version numbers of Logging operator,
> for example: ghcr.io/kube-logging/logging-operator/fluentd:5.1.1-base/filters/full

feat: add new images for logging operator

---

modules/auth/images.yml

Disable gangway's image sync, the upstream image has been removed and this makes the sync job fail:
```
time="2025-05-16T02:37:05Z" level=fatal msg="initializing source docker://gcr.io/heptio-images/gangway:v3.2.0: unable to retrieve auth token: invalid username/password: denied: Project heptio-images has been deleted."
```

fix(auth): disable gangway

---

modules/kafka/images.yml

This PR adds Strimzi Kafka Operator images for versions `0.42.0`, `0.45.0` and `0.46.0` to the SD Container Image Sync
- Added version `0.42.0` of Strimzi Operator with all supported Kafka versions (`3.6.0`, `3.6.1`, `3.6.2`, `3.7.0`, `3.7.1`)
- Added version `0.45.0` of Strimzi Operator with all supported Kafka versions (`3.8.0`, `3.8.1`, `3.9.0`)
- Added version `0.46.0` of Strimzi Operator with all supported Kafka versions (`3.9.0`, `4.0.0`)
- Added version `0.42.0`,`0.45.0`,`0.46.0` of Kaniko Executor and Maven Builder 

feat: add kafka images for operator versions 0.42.0, 0.45.0, 0.46.0

---

modules/monitoring/images.yml

Remove old prometheus-adapter image that is not available anymore on Quay.io and makes CI fail.

fix(monitoring): remove old prometheus-adapter
